export enum Role {
  MASTER_ADMIN = "MASTER_ADMIN",
  ADMIN = "ADMIN",
  USER = "USER"
}

export enum Status {
  PAYMENT_PENDING = "PAYMENT_PENDING",
  PENDING = "PENDING",
  SHIPPED = "SHIPPED",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED",
  COMPLETED = "COMPLETED"
}

export enum Priority {
  NORMAL = "NORMAL",
  URGENT = "URGENT"
}